### ISSUE TITLE
Add Favicon

### ISSUE THREAD

**Issue by AaronSofaer** [DevProgress/more-tacos#54] opened 2016-09-10 19:15 UTC
Currently, there's no favicon. This means that in OSX Chrome, the tab won't have a neat little taco truck icon!

Also, it's a 404 in the console and it's untidy.

**Comment by kielni** [comment] 2016-09-10 19:50
duplicate of https://github.com/DevProgress/more-tacos/issues/41

**Closed as completed by kielni** 2016-09-10 19:50 UTC
Labels: enhancement
